name:                hnefatafl
version:             0.0.0.1
github:              "ftzm/hnefatafl"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ftzm/hnefatafl#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers
- vector
- vector-th-unbox
- unix
- mtl
- ansi-terminal
- aeson
- aeson-pretty
- bytestring
- unordered-containers
- lens
- optparse-applicative
- brick
- vty
- async


library:
  source-dirs: src
  ghc-options:
  # - -W
  - -Werror

executables:
  hnefatafl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hnefatafl
